### PR TITLE
coffeescript dependency updated

### PR DESCRIPTION
**Pull request by andrzejsliwa**
gem dependency updated for using current version of coffee-script gem

### CODE REVIEW

**Comment by quirkey** [comment]
Pulled. Thanks!

**Comment by kljohann** [comment]
Aren't you supposed to edit the Rakefile (and Gemfile?) instead?

**Comment by quirkey** [comment]
ack - you're right. I'll update this before the next release.

**Comment by andrzejsliwa** [comment]
Hi Guys, you have right, my fault ... I was not check that gemspec is auto generated by Jeweler. I will fix it asap.

**Pull request closed without merging**
