### PR TITLE
Write json-files as json into the document

### PR DESCRIPTION
**Pull request by nikuph**
I guess its better to save json files directly as json into the document so you don't have to parse them in you couchapp afterwards.

### CODE REVIEW

**Comment by helgri** [comment]
great patch

+1

**Comment by Shoom** [comment]
This is how it should have been in the first place.

**Comment by robmak** [comment]
Hell yeah. Need this!

**Comment by quirkey** [comment]
Thanks! Will release a new version soon.

**Comment by helgri** [comment]
Hey, any updates regarding the new release? :-)

**Comment by quirkey** [comment]
I know it took forever - but finally pushed a new version today (0.3.0) that includes a bunch of changes.

**Pull request merged**
